source 'https://gitee.com/mirrors/CocoaPods-Specs.git'

platform :ios, '12.0'

target 'WhyYouLying' do
  pod 'AppLovinMediationFacebookAdapter'
  pod 'AppLovinMediationGoogleAdapter'
  pod 'AppLovinMediationIronSourceAdapter'
  pod 'AppLovinMediationUnityAdsAdapter'
  pod 'AppLovinMediationVungleAdapter'
  pod 'AppLovinSDK'
  pod 'Masonry'
  pod 'Flurry-iOS-SDK/FlurrySDK'
  pod 'AppLovinMediationChartboostAdapter'
  pod 'AppLovinMediationCSJAdapter'
  pod 'AppLovinMediationFyberAdapter'
  pod 'AppLovinMediationGoogleAdManagerAdapter'
  pod 'AppLovinMediationInMobiAdapter'
  pod 'AppLovinMediationMintegralAdapter'
  pod 'AppLovinMediationAmazonAdMarketplaceAdapter'
  pod 'AmazonPublisherServicesSDK'
end
