#source 'https://gitee.com/mirrors/CocoaPods-Specs.git'
source 'https://cdn.cocoapods.org/'
platform :ios, '12.0'

target 'SplitPics' do
    pod 'GPUImage'
    pod 'MBProgressHUD'
    pod 'NYXImagesKit'
    pod 'FXBlurView'
    pod 'Masonry'
    pod 'SVProgressHUD'
    pod 'Flurry-iOS-SDK/FlurrySDK'

    pod 'AppLovinSDK'
    pod 'AppLovinMediationFacebookAdapter'
    pod 'AppLovinMediationGoogleAdapter'
    pod 'AppLovinMediationIronSourceAdapter'
    pod 'AppLovinMediationUnityAdsAdapter'
    pod 'AppLovinMediationVungleAdapter'
    pod 'AppLovinMediationGoogleAdManagerAdapter'
    pod 'AppLovinMediationMintegralAdapter'
    pod 'AppLovinMediationFyberAdapter'
    pod 'AppLovinMediationChartboostAdapter'
    pod 'AppLovinMediationInMobiAdapter'

    pod 'AppLovinMediationAmazonAdMarketplaceAdapter'
    pod 'AmazonPublisherServicesSDK'
end

