#source 'https://gitee.com/mirrors/CocoaPods-Specs.git'

platform :ios, '12.0'

target 'QRReader' do
    pod 'AppLovinMediationFacebookAdapter'
    pod 'AppLovinMediationGoogleAdapter'
    pod 'AppLovinMediationIronSourceAdapter'
    pod 'AppLovinMediationUnityAdsAdapter'
    pod 'AppLovinMediationVungleAdapter'
    pod 'AppLovinSDK'
    pod 'Flurry-iOS-SDK/FlurrySDK'
    pod 'Masonry'
    pod 'AppLovinMediationGoogleAdManagerAdapter'
    pod 'AppLovinMediationMintegralAdapter'
    pod 'AppLovinMediationFyberAdapter'
    pod 'AppLovinMediationChartboostAdapter'
    pod 'AppLovinMediationInMobiAdapter'  
end
