#source 'https://gitee.com/mirrors/CocoaPods-Specs.git'
platform :ios, '12.0'

target 'Mahjong' do
    pod 'AppLovinMediationAdColonyAdapter'
    pod 'AppLovinMediationTapjoyAdapter'
    pod 'AppLovinMediationFacebookAdapter'
    pod 'AppLovinMediationGoogleAdapter'
    pod 'AppLovinMediationIronSourceAdapter'
    pod 'AppLovinMediationUnityAdsAdapter'
    pod 'AppLovinMediationVungleAdapter'
    pod 'AppLovinSDK'
    pod 'Flurry-iOS-SDK/FlurrySDK'
    pod 'Masonry'
    pod 'AppLovinMediationGoogleAdManagerAdapter'
    pod 'AppLovinMediationMintegralAdapter'
    pod 'AppLovinMediationFyberAdapter'
    pod 'AppLovinMediationChartboostAdapter'
    pod 'AppLovinMediationInMobiAdapter'
    pod 'AppLovinMediationMintegralAdapter'
    pod 'AppLovinMediationAmazonAdMarketplaceAdapter'
    pod 'AmazonPublisherServicesSDK'  
end



